"use client";

import { Box, Container, Heading, Text, Stack } from "@chakra-ui/react";

export default function PrivacyPolicy() {
  return (
    <Container maxW="4xl" py={16} color="#141414">
      <Stack gap={6}>
        <Heading size="lg" textAlign="center">
          Privacy Policy
        </Heading>

        <Text fontWeight="bold">Last Updated: 06/12/2025</Text>

        {/* 1. Introduction */}
        <Heading size="md" mt={8}>
          1. Introduction
        </Heading>

        <Text>
          Welcome to Fitness Space. We are committed to protecting your privacy
          and being transparent about how we handle your information. This
          Privacy Policy explains what data we collect, why we collect it, and
          how we use it to provide our coaching, workout, and community
          services.
        </Text>

        <Text>
          By using Fitness Space, you agree to the practices described in this
          policy.
        </Text>

        {/* 2. Info We Collect */}
        <Heading size="md" mt={8}>
          2. Information We Collect
        </Heading>

        <Text>
          We collect the following categories of information to provide and
          improve our service:
        </Text>

        <Box pl={4}>
          <Text>
            <strong>Account Information:</strong> Your name, email address, and
            password when you create an account.
          </Text>

          <Text>
            <strong>Health and Fitness Information (Sensitive Data):</strong>{" "}
            Information you provide, such as your weight, dietary preferences,
            medical conditions, and health goals. This also includes data
            generated by your activity, such as workout logs, completed
            exercises, and food entries.
          </Text>

          <Text>
            <strong>Community Content:</strong> Any messages, posts, or photos
            you share in the community forums.
          </Text>

          <Text>
            <strong>Technical and Usage Data:</strong> Information collected
            automatically, such as your IP address, device type, and how you
            interact with the app (e.g., features used, time spent). This data
            is often aggregated and anonymized for analytics.
          </Text>
        </Box>

        {/* 3. How We Use */}
        <Heading size="md" mt={8}>
          3. How We Use Your Information
        </Heading>

        <Text>
          We use your information for the following specific purposes:
        </Text>

        <Box pl={4}>
          <Text>
            <strong>To Provide and Personalize the Service:</strong> We use your
            Health and Fitness Information to create your personalized meal and
            workout plans and track your progress.
          </Text>

          <Text>
            <strong>To Facilitate Coaching:</strong> We use your Health and
            Fitness Information and Community Content to enable our coaches to
            provide you with guidance and feedback.
          </Text>

          <Text>
            <strong>To Enable Community:</strong> We use your Community Content
            to operate the community forums and display your posts with your
            data hidden.
          </Text>

          <Text>
            <strong>To Communicate with You:</strong> We use your Account
            Information to send you service-related announcements and support.
          </Text>

          <Text>
            <strong>To Improve Our Service:</strong> We use Technical and Usage
            Data to analyze trends and improve the app's performance and user
            experience.
          </Text>
        </Box>

        {/* 4. Sharing */}
        <Heading size="md" mt={8}>
          4. How We Share Your Information
        </Heading>

        <Text>
          We do not and will never sell your personal data. We only share your
          information in the following limited circumstances:
        </Text>

        <Box pl={4}>
          <Text>
            <strong>With Your Consent:</strong> For example, when you post in
            the community, your content becomes visible to other users.
          </Text>

          <Text>
            <strong>With Service Providers:</strong> We share data with strictly
            vetted companies that help us operate, such as:
          </Text>

          <Box pl={6}>
            <Text>
              • <strong>Cloud Hosting Providers</strong> (e.g., Amazon Web
              Services) to store your data securely.
            </Text>
            <Text>
              • <strong>Analytics Providers</strong> (e.g., Google Analytics) to
              understand how the app is used and improve our service. This data
              is aggregated and anonymized where possible.
            </Text>
            <Text>
              • <strong>Payment Processors</strong> (e.g., Paystack) to handle
              your subscription payments. We do not store your payment card
              details.
            </Text>
          </Box>

          <Text>
            <strong>For Legal Reasons:</strong> If required by law or necessary
            to protect our rights or user safety.
          </Text>
        </Box>

        {/* 5. Security */}
        <Heading size="md" mt={8}>
          5. Data Security
        </Heading>

        <Text>
          We implement industry-standard security measures to protect your
          personal information from unauthorized access, alteration, or
          destruction. However, no method of transmission over the Internet is
          100% secure, and we cannot guarantee absolute security.
        </Text>

        {/* 6. Rights */}
        <Heading size="md" mt={8}>
          6. Your Rights
        </Heading>

        <Text>You have control over your personal data. You can:</Text>

        <Box pl={4}>
          <Text>
            <strong>Access &amp; Correction:</strong> View and update much of
            your personal data directly in the app via your profile settings.
          </Text>

          <Text>
            <strong>Data Portability:</strong> Request a copy of your personal
            data in a machine-readable format at support@getfitness.space.
          </Text>

          <Text>
            <strong>Deletion:</strong> Request the deletion of your account and
            personal data by contacting us at support@getfitness.space.
          </Text>
        </Box>

        <Text>
          We will respond to all requests in accordance with applicable law.
        </Text>

        <Heading size="sm" mt={6}>
          Additional GDPR/UK Rights
        </Heading>

        <Text>
          If you are located in the European Union or United Kingdom, you also
          have the following rights:
        </Text>

        <Box pl={4}>
          <Text>
            <strong>Right to Object:</strong> You may object to the processing
            of your personal data for certain purposes, such as direct
            marketing.
          </Text>

          <Text>
            <strong>Right to Restrict Processing:</strong> You may request that
            we limit how we process your data in certain circumstances.
          </Text>

          <Text>
            <strong>Right to Lodge a Complaint:</strong> You have the right to
            lodge a complaint with your local data protection authority if you
            believe your rights have been violated.
          </Text>
        </Box>

        <Heading size="sm" mt={6}>
          California Privacy Rights (CCPA)
        </Heading>

        <Text>
          If you are a resident of California, you have the following rights
          under the California Consumer Privacy Act (CCPA):
        </Text>

        <Box pl={4}>
          <Text>
            <strong>Right to Know:</strong> You may request disclosure of the
            categories and specific pieces of personal information we collect
            about you.
          </Text>

          <Text>
            <strong>Right to Delete:</strong> You may request deletion of your
            personal information, subject to certain exceptions.
          </Text>

          <Text>
            <strong>Right to Opt Out of Sale:</strong> Although we do not sell
            personal data, you have the right to opt out of any future sale of
            your personal information.
          </Text>

          <Text>
            <strong>Right to Non-Discrimination:</strong> You will not be
            discriminated against for exercising your privacy rights.
          </Text>
        </Box>

        {/* 7. Legal Basis */}
        <Heading size="md" mt={8}>
          7. Legal Basis for Processing (GDPR/UK)
        </Heading>

        <Text>
          We process your personal data under the following legal bases:
        </Text>

        <Box pl={4}>
          <Text>
            <strong>Consent:</strong> When you provide health and fitness
            information or community content, you consent to our use of this
            data to personalize your experience.
          </Text>

          <Text>
            <strong>Contract:</strong> When you subscribe to our Service,
            processing your account and payment information is necessary to
            fulfill our contractual obligations.
          </Text>

          <Text>
            <strong>Legitimate Interests:</strong> We may process technical and
            usage data to improve our Service and ensure security, provided such
            interests are not overridden by your rights.
          </Text>

          <Text>
            <strong>Legal Obligations:</strong> We may process or disclose data
            where required by applicable law.
          </Text>
        </Box>

        {/* 8. International Transfers */}
        <Heading size="md" mt={8}>
          8. International Data Transfers
        </Heading>

        <Text>
          Our service providers may be located in countries outside of your own.
          We ensure that appropriate legal safeguards are in place to protect
          your data when such transfers occur, in accordance with applicable
          data protection laws.
        </Text>

        {/* 9. Cookies */}
        <Heading size="md" mt={8}>
          9. Cookies &amp; Tracking Technologies
        </Heading>

        <Text>
          We use cookies and similar tracking technologies to improve your
          experience, analyze usage, and deliver personalized content. Cookies
          are small files stored on your device. You can manage or disable
          cookies through your browser settings. Please note that disabling
          cookies may affect the functionality of the Service.
        </Text>

        {/* 10. Data Retention */}
        <Heading size="md" mt={8}>
          10. Data Retention
        </Heading>

        <Text>
          We retain personal data only for as long as necessary to provide the
          Service, comply with legal obligations, resolve disputes, and enforce
          agreements. Health and fitness data may be retained for the duration
          of your subscription and deleted upon account closure, unless longer
          retention is required by law.
        </Text>

        {/* 11. Children */}
        <Heading size="md" mt={8}>
          11. Children's Privacy
        </Heading>
        <Text>
          Fitness Space is not intended for users under the age of 16. We do not
          knowingly collect personal information from children under 16.
        </Text>

        {/* 12. Changes */}
        <Heading size="md" mt={8}>
          12. Changes to This Policy
        </Heading>

        <Text>
          We may update this policy from time to time. We will notify you of any
          material changes by posting the new policy on this site and updating
          the "Last Updated" date. Your continued use of the Service after such
          changes constitutes your acceptance of the new policy.
        </Text>

        {/* 13. Contact */}
        <Heading size="md" mt={8}>
          13. Contact Us
        </Heading>

        <Text>
          If you have any questions about this Privacy Policy, please contact us
          at: info@getfitness.space.
        </Text>

        <Text>No 48, Kenneth Street, Achara Layout, Enugu, Enugu State.</Text>
      </Stack>
    </Container>
  );
}
